[global]
# Development mode - set to false to avoid port conflicts
developmentMode = false
# Show warning when running in development mode
showWarningOnDirectExecution = false

[server]
# Server settings
port = 8501
enableCORS = false
enableXsrfProtection = false
# File watcher settings
fileWatcherType = "auto"
headless = false
# Upload settings
maxUploadSize = 50
maxMessageSize = 50

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Custom theme colors
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"